Updated github actions to use pnpm

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -20,9 +20,23 @@ env:
   CODECOV_UNIQUE_NAME: CODECOV_UNIQUE_NAME-${{ github.run_id }}-${{ github.run_number }}
 
 jobs:
-  Test-Docusaurus-Deployment:
-    name: Test Deployment to https://docs-plugin.talawa.io
+  Code-Quality-Checks:
+    name: Performs linting, formatting, type-checking, checking for different source and target branch
     runs-on: ubuntu-latest
+    steps:
+      - name: Check if the source and target branches are different
+        if: ${{ github.event.pull_request.base.ref == github.event.pull_request.head.ref }}
+        run: |
+          echo "Source Branch ${{ github.event.pull_request.head.ref }}"
+          echo "Target Branch ${{ github.event.pull_request.base.ref }}"
+          echo "Error: Source and Target Branches are the same. Please ensure they are different."
+          echo "Error: Close this PR and try again."                    
+          exit 1
+
+  Test-Docusaurus-Deployment:
+    name: Test Deployment to https://developer.palisadoes.org
+    runs-on: ubuntu-latest
+    needs: [Code-Quality-Checks]
     strategy:
       matrix:
         node-version: ['24.x']
